# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Simon Wilson
email: simoncwilson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Simon Wilson: service, user experience and interaction designer and maker of people-centred digital things.
baseurl: "" # the subpath of your site, e.g. /blog
permalink: /:title

url: "https://www.ermlikeyeah.com/" # the base hostname & protocol for your site

# Accounts elsewhere usernames to link to
github_username:  ermlikeyeah
instagram_username: idlesi
linkedin_username: siwilson
pinboard_username: idlesi
speakerdeck_username: idlesi
twitter_username: ermlikeyeah


# Build settings
markdown: kramdown

# Gems
# gems: [jekyll-paginate]
